spring:
  mail:
    password: ${mingri.mail.password}
    host: ${mingri.mail.host}
    port: ${mingri.mail.port}
    username: ${mingri.mail.user}
    from: ${mingri.mail.from}
    expireTime: ${mingri.mail.expireTime}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
