spring:
  datasource:
    url: jdbc:mysql://${mingri.datasource.master.host}:${mingri.datasource.master.port}/${database.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${mingri.datasource.master.username}
    password: ${mingri.datasource.master.password}
  dynamic:
    primary: master
    datasource:
      master:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://${mingri.datasource.master.host}:${mingri.datasource.master.port}/${database.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: ${mingri.datasource.master.username}
        password: ${mingri.datasource.master.password}
      slave:
        # 数据库名，从配置 database.name 中获取
        url: jdbc:mysql://${mingri.datasource.slave.host}:${mingri.datasource.slave.port}/${database.name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
        username: ${mingri.datasource.slave.username}
        password: ${mingri.datasource.slave.password}
  data:
    redis:
      host: ${mingri.redis.host}
      port: ${mingri.redis.port}
      password: ${mingri.redis.password}
      database: ${mingri.redis.database}

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl