mingri:
  datasource:
    master:
      host:
      port: 3339
      database: mini-chat
      username: root
      password: 123456
    slave:
      host:
      port: 3340
      database: mini-chat
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name:
  mail:
    from: xxxx@qq.com
    password:
    host: smtp.qq.com
    port: 465
    user: xxxx@qq.com
    expireTime: 180 #3分钟
  jwt:
    secret-key: csd_admin
    expire-time: 7200000
    token-name: x-token
  doubao:
    api-key:
    count-limit: 0
    length-limit: 50
    model: ep-20250130211307-qgfnq


