server:
  port: 8848

spring:
  application:
    name: mini-chat
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai
  main:
    allow-circular-references: true
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://${mingri.datasource.master.host}:${mingri.datasource.master.port}/${mingri.datasource.master.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
          username: ${mingri.datasource.master.username}
          password: ${mingri.datasource.master.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 70000
#        slave:
#          url: jdbc:mysql://${mingri.datasource.slave.host}:${mingri.datasource.slave.port}/${mingri.datasource.slave.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#          username: ${mingri.datasource.slave.username}
#          password: ${mingri.datasource.slave.password}
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            max-lifetime: 70000


  data:
    redis:
      host: ${mingri.redis.host}
      port: ${mingri.redis.port}
      password: ${mingri.redis.password}
      database: ${mingri.redis.database}
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true



#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.mingri.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.mingri.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: del_flag # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
  configuration:
    # 全局枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

logging:
  level:
    com:
      mingri:
        mapper: debug
        service: info
        controller: info

mingri:
  alioss:
    endpoint: ${mingri.alioss.endpoint}
    access-key-id: ${mingri.alioss.access-key-id}
    access-key-secret: ${mingri.alioss.access-key-secret}
    bucket-name: ${mingri.alioss.bucket-name}

captcha:
  email:
    from: ${mingri.mail.from}
    password: ${mingri.mail.password}
    host: ${mingri.mail.host}
    port: ${mingri.mail.port}
    user: ${mingri.mail.user}
    expire-time: ${mingri.mail.expireTime}

security:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${mingri.jwt.secret-key}
    # 设置jwt过期时间
    expire-time: ${mingri.jwt.expire-time}
    # 设置前端传递过来的令牌名称
    token-name: ${mingri.jwt.token-name}


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


## 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
#        enable: true
        # redis host
        host: ${mingri.redis.host}
        # redis port
        port: ${mingri.redis.port}
        password: ${mingri.redis.password}


mini-chat:
  limit: 100 #在线人数限制
  name: 聊天室 #群聊名称
  expires: 7 #数据过期时间（天）
  doubao: #豆包
    api-key: ${mingri.doubao.api-key}
    count-limit: ${mingri.doubao.count-limit}
    length-limit: ${mingri.doubao.length-limit}
    model: ${mingri.doubao.model}



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mingri.controller

knife4j:
  enable: true
  #是否启用接口文档登录认证
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 客户端模块

