server:
  port: 8848

spring:
  application:
    name: mini-chat
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai

  config:
    import:
      - application-dal.yml
      - application-email.yml
      - application-rabbitmq.yml
      - application-ai.yml

  mail:
    password: ${mingri.mail.password}
    host: ${mingri.mail.host}
    port: ${mingri.mail.port}
    username: ${mingri.mail.user}
    from: ${mingri.mail.from}
    expireTime: ${mingri.mail.expireTime}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://${mingri.datasource.master.host}:${mingri.datasource.master.port}/${mingri.datasource.master.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
          username: ${mingri.datasource.master.username}
          password: ${mingri.datasource.master.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 70000
#        slave:
#          url: jdbc:mysql://${mingri.datasource.slave.host}:${mingri.datasource.slave.port}/${mingri.datasource.slave.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#          username: ${mingri.datasource.slave.username}
#          password: ${mingri.datasource.slave.password}
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            max-lifetime: 70000

  data:
    redis:
      host: ${mingri.redis.host}
      port: ${mingri.redis.port}
      password: ${mingri.redis.password}
      database: ${mingri.redis.database}
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.mingri.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.mingri.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: del_flag # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
  configuration:
    # 全局枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

logging:
  level:
    com:
      mingri:
        mapper: debug
        service: info
        controller: info

minio:
  endpoint: ${mingri.minio.endpoint}
  access-key: ${mingri.minio.accessKey}
  secret-key: ${mingri.minio.secretKey}
  bucket-name: ${mingri.minio.bucketName}
  file-bucket-name: ${mingri.minio.fileBucketName}


security:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${mingri.jwt.secret-key}
    # 设置jwt过期时间
    expire-time: ${mingri.jwt.expire-time}
    # 设置前端传递过来的令牌名称
    token-name: ${mingri.jwt.token-name}


rocketmq:
  enabled: false
  name-server: 117.72.48.167:9876
  producer:
    group: linyu_group
    send-message-timeout: 5000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mingri.controller

knife4j:
  enable: true
  #是否启用接口文档登录认证
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 客户端模块

