mingri:
  datasource:
    master:
      host: 127.0.0.1
      port: 3306 #3339
      username: root
      password: 123456
    slave:
      host: 127.0.0.1
      port: 3340
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
  mail:
    from: 3116430062@qq.com
    password:
    host: smtp.qq.com
    port: 465
    user: 3116430062@qq.com
    expireTime: 180 #3分钟
  minio:
    endpoint: http://127.0.0.1:9000
    bucketName: chat
    fileBucketName: file
    accessKey:
    secretKey:
  rocketmq:
    enabled: true
    name-server: 127.0.0.1:9876
    group: mingri_group
  jwt:
    secret-key: csd_admin
    expire-time: 7200000
    token-name: x-token
#  ai:
#    datasource:
#      base-url: 127.0.0.1:3306
#      database: ai-rag-knowledge
#      username: root
#      password: 123456
#    ollama:
#      base-url: http://127.0.0.1:11434
#    openai:
#      base-url: https://api.xiaoai.plus
#      api-key: