server:
  port: 9200

spring:
  application:
    name: SAI-Chat
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import:
      - application-ai.yml
      - application-dal.yml
      - application-email.yml
      - application-middleware.yml
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai

database:
  name: sai-chat

knife4j:
  enable: true
  #是否启用接口文档登录认证
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 客户端请求对象














